. "$PSScriptRoot\Functions\GenXdev.Windows.WireGuard\Add-WireGuardPeer.ps1"
. "$PSScriptRoot\Functions\GenXdev.Windows.WireGuard\EnsureWireGuard.ps1"
. "$PSScriptRoot\Functions\GenXdev.Windows.WireGuard\Get-WireGuardPeerQRCode.ps1"
. "$PSScriptRoot\Functions\GenXdev.Windows.WireGuard\Get-WireGuardPeers.ps1"
. "$PSScriptRoot\Functions\GenXdev.Windows.WireGuard\Get-WireGuardStatus.ps1"
. "$PSScriptRoot\Functions\GenXdev.Windows.WireGuard\Remove-WireGuardPeer.ps1"
. "$PSScriptRoot\Functions\GenXdev.Windows.WireGuard\Reset-WireGuardConfiguration.ps1"
